const data = [
  {
    departure: "Beograd",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Novi Sad",
    price: 500,
  },
  {
    departure: "Beograd",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Niš",
    price: 900,
  },
  {
    departure: "Beograd",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Zrenjanin",
    price: 400,
  },
  {
    departure: "Beograd",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Pančevo",
    price: 200,
  },
  {
    departure: "Beograd",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Stari Slankamen",
    price: 480,
  },
  {
    departure: "Beograd",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Budimpešta",
    price: 2800,
  },
  {
    departure: "Beograd",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Beč",
    price: 3200,
  },
  {
    departure: "Beograd",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Novi Sad",
    price: 500,
  },
  {
    departure: "Beograd",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Niš",
    price: 900,
  },
  {
    departure: "Beograd",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Zrenjanin",
    price: 400,
  },
  {
    departure: "Beograd",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Pančevo",
    price: 200,
  },
  {
    departure: "Beograd",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Novi Sad",
    price: 500,
  },
  {
    departure: "Beograd",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Niš",
    price: 900,
  },
  {
    departure: "Smederevo",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Beograd",
    price: 400,
  },
  {
    departure: "Smederevo",
    timeD: "8:45",
    timeA: "16:00",
    arrival: "Beograd",
    price: 400,
  },
  {
    departure: "Smederevo",
    timeD: "8:45",
    timeA: "10:00",
    arrival: "Beograd",
    price: 400,
  },
  {
    departure: "Smederevo",
    timeD: "18:45",
    timeA: "10:00",
    arrival: "Beograd",
    price: 400,
  },
  {
    departure: "Smederevo",
    timeD: "8:45",
    timeA: "10:00",
    arrival: "Beograd",
    price: 400,
  },
  {
    departure: "Smederevo",
    timeD: "8:45",
    timeA: "10:00",
    arrival: "Beograd",
    price: 400,
  },
  {
    departure: "Smederevo",
    timeD: "8:45",
    timeA: "11:00",
    arrival: "Pančevo",
    price: 200,
  },
];
export default data;
